spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://postgresql:5432/
    user: postgres
    password: postgres
  security:
    user:
      name: dev
      password: dev