#######################
##### BuildConfig #####
#######################
kind: BuildConfig
apiVersion: v1
metadata:
  name: backend
  labels:
    application: backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/reaper1617/spring-rest-minishift-demo.git
      ref: master
    contextDir: ""
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: openjdk18-openshift:latest
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
  triggers:
#    todo: fix wrong syntax
#    - type: GitHub
#      generic:
#        secret: secret
#    - type: Generic
#      github:
#        secret: secret
    - type: ImageChange
      imageChange: {}